### ISSUE TITLE
[Bug] Wrong file names on Mac

### ISSUE THREAD

**Issue by Berezhnyk** [dutchgrit/afasclient#6]
On Mac, it creates a Connectors folder and files that start with the word `Connectors\`.
Example file name (not path) `Connectors\KnContact.cs`

**Comment by LucasVos** [comment]
It should be solved. Please upgrade the afas-cli tool before trying it with:
```
dotnet tool update afas-cli --global
```

**Comment by Berezhnyk** [comment]
Thank you for the response. It looks like the issue is not resolved yet. 
I have updated the tool 
![CleanShot 2024-12-20 at 11 02 51@2x](https://github.com/user-attachments/assets/57ff9239-9d41-4fed-94b7-ee2e61968dd6)
And run the command to generate the models
`afas-cli generate --namespace MyApp.Infrastructure.Connectors --useInternal`

But the file names are incorrect:
![CleanShot 2024-12-20 at 11 04 05@2x](https://github.com/user-attachments/assets/92295ac8-eef4-4007-b3d8-0f759a4c0942)

**Comment by Rokimajo** [comment]
Hello Berezhnyk, this issue should now be fixed in version `1.0.41`, we apologize for the inconvenience.
Please first update your afas-cli tool using `dotnet tool update afas-cli --global` and try generating your connectors again.

![image](https://github.com/user-attachments/assets/8a129e8d-d992-4c5d-8821-c7454ec3fdc7)

Now when generating your connectors, it should be OS-independent _(test screenshot shown using Ubuntu v24.04)_

![image](https://github.com/user-attachments/assets/28322203-f6ca-4647-bcf8-543d6264efb3)
![image](https://github.com/user-attachments/assets/f36bfbe0-546a-406d-9d6b-e13211de5f0c)
